In [2]:
from effects_table import Experiment2N
import numpy as np
import pandas as pd

# Validation
The below validates the "Experiment2N Class" against examples from the class slides

In [6]:
#2^3 experiment handout 5, pages 4-7
exp = Experiment2N(factors=['Temp','Conc','Catlst'], block_size=0)
exp_table = exp.generate_table()
exp_table

,Temp,Conc,Catlst,Temp_contrast,Conc_contrast,Catlst_contrast,TempConc_contrast,TempCatlst_contrast,ConcCatlst_contrast,TempConcCatlst_contrast
0,0,0,0,-1,-1,-1,1,1,1,-1
1,1,0,0,1,-1,-1,-1,-1,1,1
2,0,1,0,-1,1,-1,-1,1,-1,1
3,1,1,0,1,1,-1,1,-1,-1,-1
4,0,0,1,-1,-1,1,1,-1,-1,1
5,1,0,1,1,-1,1,-1,1,-1,-1
6,0,1,1,-1,1,1,-1,-1,1,-1
7,1,1,1,1,1,1,1,1,1,1

In [8]:
exp_results = exp_table[['Temp','Conc','Catlst']]
exp_results['y'] = [60, 72, 54, 68, 52, 83, 45, 80]
effects = exp.calculate_effects(exp_results, response_col='y')
effects.loc['mean_square'] = effects.loc['std_effect',:]**2
effects

C:\Users\aburtnerabt\AppData\Local\Temp\ipykernel_46388\3880048586.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  exp_results['y'] = [60, 72, 54, 68, 52, 83, 45, 80]

,Temp_effect,Conc_effect,Catlst_effect,TempConc_effect,TempCatlst_effect,ConcCatlst_effect,TempConcCatlst_effect
effect,92.000000,-20.000000,6.00000,6.00000,40.000000,0.0,2.000000
std_effect,32.526912,-7.071068,2.12132,2.12132,14.142136,0.0,0.707107
mean_square,1058.000000,50.000000,4.50000,4.50000,200.000000,0.0,0.500000